# Generated by Django 3.0.5 on 2020-04-28 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import slides.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presentation',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('image', models.ImageField(upload_to=slides.models.get_image_saving_path)),
                ('audio', models.FileField(upload_to=slides.models.get_audio_saving_path)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Presentation')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('agreement', models.CharField(choices=[('AA', 'Agree'), ('DA', 'Disagree'), ('PA', 'Partial Agree')], max_length=2)),
                ('suggestion', models.TextField()),
                ('comment', models.TextField()),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Slide')),
            ],
        ),
    ]
